# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Add Two Numbers
#'
#' Return the sum of two numbers.
#' @param x
#' @param y
#' @export
add_cpp <- function(x, y) {
    .Call(`_pkgrcpp_add_cpp`, x, y)
}

approx_pi <- function(N) {
    .Call(`_pkgrcpp_approx_pi`, N)
}

approx_pi_dq <- function(N) {
    .Call(`_pkgrcpp_approx_pi_dq`, N)
}

inner_prod <- function(x, y) {
    .Call(`_pkgrcpp_inner_prod`, x, y)
}

#' Add a Vector of Numbers
#'
#' Return the sum of a vector.
#' @param x A numeric vector
#' @examples sumC(c(1, 3, 6))
#' @export
sumC <- function(x) {
    .Call(`_pkgrcpp_sumC`, x)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_pkgrcpp_RcppExport_registerCCallable', PACKAGE = 'pkgrcpp')
})
